### PR TITLE
Mongo 4 needs protocol version=1

### PR DESCRIPTION
**Pull request by wallyworld**
When initialising a replicaset on mongo 4.x, the protocol version needs to be 1, not 0.

### CODE REVIEW

**Review by jameinel — APPROVED** [review]
It seems we aren't seeing this with the builds of Mongo we use on Ubuntu, but apparently there is a docker image that now mandates the flag be set.
It is true that pv = 1 has been default for 3.2+, but apparently now they want you to know that it is default.
I wonder if they are looking at a pv=2 and want people to be explicitly declaring it before they do so.

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
